export enum AsyncActionType {
  Email,
  RegistryCompanyCreate,
  IssueCredit,
  AuthProgramme,
  RejectProgramme,
  DocumentUpload,
  ProgrammeCreate,
  ProgrammeAccept,
  AddMitigation,
  OwnershipUpdate,
  CADTProgrammeCreate,
  CADTProgrammeStatusChange,
  CADTCreditIssue,
  CADTCertify,
  CADTTransferCredit,
  CADTRetireCredit,
}
