export const EmissionSectors: any = {
  'Energy Industries': 'energyIndustries',
  'Manufacturing Industries and Construction': 'manufacturingIndustriesConstruction',
  Transport: 'transport',
  'Other Sectors': 'otherSectors',
  'Non-Specified': 'nonSpecified',
  'Solid Fuels': 'solidFuels',
  'Oil and Natural Gas': 'oilNaturalGas',
  'Other emissions from Energy Production': 'otherEmissionsEnergyProduction',
  'Transport of CO2': 'transportOfCo2',
  'Injection and Storage': 'injectionStorage',
  'Other (Carbon dioxide Transport and Storage)': 'otherCarbonDioxideTransportStorage',
  'Mineral Industry': 'mineralIndustry',
  'Chemical Industry': 'chemicalIndustry',
  'Metal Industry': 'metalIndustry',
  'Non-Energy Products from Fuels and Solvent Use': 'nonEnergyProductsFuelsSolventUse',
  'Electronics Industry': 'electronicsIndustry',
  'Product Uses as Substitutes for Ozone Depleting Substances':
    'productUsesSubstOzoneDepletingSubs',
  'Other Product Manufacture and Use': 'otherProductManufactureUse',
  'Other (Industrial Processes & Product Use)': 'otherIndustrialProcessesProductUse',
  Livestock: 'livestock',
  Land: 'land',
  'Aggregate sources and non-CO2 emissions sources on land': 'aggregateNonCo2SourcesLand',
  'Other (Agriculture, Forestry, and Other Land Use)': 'otherAgricultureForestryOtherLandUse',
  'Solid Waste Disposal': 'solidWasteDisposal',
  'Biological Treatment of Solid Waste': 'biologicalTreatmentSolidWaste',
  'Incineration and Open Burning of Waste': 'incinerationOpenBurningWaste',
  'Wastewater Treatment and Discharge': 'wastewaterTreatmentDischarge',
  'Other (Waste)': 'otherWaste',
  'Indirect N2O emissions from the atmospheric deposition of nitrogen in NOx and NH3':
    'indirectN2oEmissions',
  Other: 'other',
  'Total CO2 equivalent emissions without land use, land-use change and forestry':
    'totalCo2WithoutLand',
  'Total CO2 equivalent emissions with land use, land-use change and forestry': 'totalCo2WithLand',
};

export const formFields = {
  energyEmissions: {
    fuelCombustionActivities: [
      'energyIndustries',
      'manufacturingIndustriesConstruction',
      'transport',
      'otherSectors',
      'nonSpecified',
    ],
    fugitiveEmissionsFromFuels: ['solidFuels', 'oilNaturalGas', 'otherEmissionsEnergyProduction'],
    carbonDioxideTransportStorage: ['transportOfCo2', 'injectionStorage', 'other'],
  },
  industrialProcessesProductUse: [
    'mineralIndustry',
    'chemicalIndustry',
    'metalIndustry',
    'nonEnergyProductsFuelsSolventUse',
    'electronicsIndustry',
    'productUsesSubstOzoneDepletingSubs',
    'otherProductManufactureUse',
    'other',
  ],
  agricultureForestryOtherLandUse: ['livestock', 'land', 'aggregateNonCo2SourcesLand', 'other'],
  waste: [
    'solidWasteDisposal',
    'biologicalTreatmentSolidWaste',
    'incinerationOpenBurningWaste',
    'wastewaterTreatmentDischarge',
    'other',
  ],
  other: ['indirectN2oEmissions', 'other'],
};