name: Publish to NPM UI
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - package.json

jobs:
  deploy_front_end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "palinda@xeptagon.com"
          git pull origin HEAD
          yarn version --patch
          git push --follow-tags
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Version Update
          CI_COMMIT_AUTHOR: Continuous Integration
      - run: yarn run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'xeptagondev',
              repo: 'carbon-registry',
              workflow_id: 'web-lib-update.yml',
              ref: 'develop'
            })
            await github.rest.actions.createWorkflowDispatch({
              owner: 'xeptagondev',
              repo: 'carbon-registry',
              workflow_id: 'web-lib-update.yml',
              ref: 'unified'
            })
            await github.rest.actions.createWorkflowDispatch({
              owner: 'xeptagondev',
              repo: 'carbon-transparency',
              workflow_id: 'web-lib-update.yml',
              ref: 'develop'
            })
