name: Publish to NPM carbon-credit-calculator
on:
  push:
    branches:
      - main
    paths:
      - backend/carbon-credit-calculator/**

jobs:
  publish_carbon_serial_gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
        working-directory: backend/carbon-credit-calculator
      - run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "palinda@xeptagon.com"
          yarn version --patch
          git push --follow-tags
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Version Update
          CI_COMMIT_AUTHOR: Continuous Integration
        working-directory: backend/carbon-credit-calculator
      - run: yarn run build
        working-directory: backend/carbon-credit-calculator
      - run: npm publish --access public
        working-directory: backend/carbon-credit-calculator
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}